title: EE 186
description: Introduction to Embedded Systems
baseurl: "/EE186" # the subpath of your site, e.g. /blog
url: "https://ee186.github.io" # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
#repository: just-the-docs/just-the-docs # for github-metadata


# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.10.0
permalink: pretty

plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-include-cache

just_the_docs:
color_scheme: light
search_enabled: false
heading_anchors: true

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

